# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_metrics 
$character 
"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "bold blue"
show_always = true

[hostname]
ssh_only = true

[directory]
truncation_length = 0
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]

[git_state]

[git_metrics]
disabled = false
only_nonzero_diffs = false
format = '\[([+$added]($added_style))|([-$deleted]($deleted_style))\]'

[conda]
ignore_base = false
format = '\[[$environment]($style)\] '

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [$state( \($name\))](bold blue) '
